# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/assitant/assistant_on_demand.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n(proto/assitant/assistant_on_demand.proto\x12\x13\x61ssistant_on_demand\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\"(\n\x12\x43hannelMetaRequest\x12\x12\n\nchannel_id\x18\x01 \x01(\x03\"6\n\x0fPostStatRequest\x12\x12\n\nchannel_id\x18\x01 \x01(\x03\x12\x0f\n\x07post_id\x18\x02 \x01(\x03\"(\n\x12\x43hannelSubsRequest\x12\x12\n\nchannel_id\x18\x01 \x01(\x03\"2\n\x0bPostRequest\x12\x12\n\nchannel_id\x18\x01 \x01(\x03\x12\x0f\n\x07post_id\x18\x02 \x01(\x03\"$\n\rInviteRequest\x12\x13\n\x0binvite_link\x18\x01 \x01(\t2\x97\x03\n\x12\x61ssistanceOnDemand\x12Q\n\x0egetChannelMeta\x12\'.assistant_on_demand.ChannelMetaRequest\x1a\x16.google.protobuf.Empty\x12K\n\x0bgetPostStat\x12$.assistant_on_demand.PostStatRequest\x1a\x16.google.protobuf.Empty\x12Q\n\x0egetChannelSubs\x12\'.assistant_on_demand.ChannelSubsRequest\x1a\x16.google.protobuf.Empty\x12\x43\n\x07getPost\x12 .assistant_on_demand.PostRequest\x1a\x16.google.protobuf.Empty\x12I\n\x0bjoinChannel\x12\".assistant_on_demand.InviteRequest\x1a\x16.google.protobuf.Emptyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.assitant.assistant_on_demand_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_CHANNELMETAREQUEST']._serialized_start=127
  _globals['_CHANNELMETAREQUEST']._serialized_end=167
  _globals['_POSTSTATREQUEST']._serialized_start=169
  _globals['_POSTSTATREQUEST']._serialized_end=223
  _globals['_CHANNELSUBSREQUEST']._serialized_start=225
  _globals['_CHANNELSUBSREQUEST']._serialized_end=265
  _globals['_POSTREQUEST']._serialized_start=267
  _globals['_POSTREQUEST']._serialized_end=317
  _globals['_INVITEREQUEST']._serialized_start=319
  _globals['_INVITEREQUEST']._serialized_end=355
  _globals['_ASSISTANCEONDEMAND']._serialized_start=358
  _globals['_ASSISTANCEONDEMAND']._serialized_end=765
# @@protoc_insertion_point(module_scope)
